---
Name: stripesubscriptionroutes
After: framework/routes#rootroutes
---
SilverStripe\Control\Director:
  rules:
    'setupsubscription//$Action/$ID/$OtherID': 'ilateral\SilverCommerce\StripeSubscriptions\SubscriptionCheckout'

